import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '../components/Button'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          {/* Hero */}

          <div className="flex flex-col md:flex-row p-5 max-w-screen-xl items-center" >
            {/* Taglines */}

            <div className="flex-1 mb-6">
              <p className="text-xs text-secondary">Development | Code | Entrepreneurship</p>
              <h1 className="text-2xl my-3">
                I'm here to help you become a really good web developer.
              </h1>
              <p className="text-xs font-light">
                It is a long establishment fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that is has a...
              </p>
              {/* Button */}
            </div>

            {/* Videos */}

            <div className="flex-1 justify-center items-center pr-10 relative mb-10 w-full">
              
                <Image 
                  src="/images/video-image.jpg"
                  height={144}
                  width={144}
                  alt="Video Image"
                  layout="responsive"
                />
                <div className="absolute bottom-0 right-0 w-14 transform translate-y-11">
                  <Image 
                      src="/images/Pattern.svg"
                      height={313}
                      width={167}
                      alt="Video Image"
                      layout="responsive"
                    />
              </div>
            </div>
            <Button href="" text="Sign up" />
          </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
